global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web-application'
    scrape_interval: 5s
    static_configs:
      - targets: ['web_application:80']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']